array1 = [1, 2, 3; 4, 5, 6];
array2 = [7, 8, 9; 10, 11, 12];
concatenatedArray1 = [array1, array2];
disp("Array 1:");
disp(array1);
disp("Array 2:");
disp(array2);
disp("Horizontal Concatenation Result:");
disp(concatenatedArray1);
concatenatedArray2 = [array1; array2];
disp("Vertical Concatenation Result:");
disp(concatenatedArray2);